# Generated by Django 4.0.3 on 2022-03-30 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_fname', models.CharField(max_length=200)),
                ('sender_lname', models.CharField(max_length=200)),
                ('sender_contact', models.CharField(max_length=200)),
                ('sender_location', models.CharField(choices=[('N', 'Nairobi'), ('M', 'Mombasa'), ('K', 'Kisumu'), ('E', 'Embu'), ('N', 'Nakuru')], max_length=1)),
                ('parcel_description', models.CharField(max_length=200)),
                ('parcel_weight', models.CharField(choices=[('F', '0-1 kgs'), ('S', '2-5 kgs'), ('T', '6-10 kgs')], max_length=1)),
                ('receipient_fname', models.CharField(max_length=200)),
                ('receipient_lname', models.CharField(max_length=200)),
                ('receipient_contact', models.CharField(max_length=200)),
                ('receipient_location', models.CharField(choices=[('N', 'Nairobi'), ('M', 'Mombasa'), ('K', 'Kisumu'), ('E', 'Embu'), ('N', 'Nakuru')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='newdestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_location', models.CharField(choices=[('N', 'Nairobi'), ('M', 'Mombasa'), ('K', 'Kisumu'), ('E', 'Embu'), ('N', 'Nakuru')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Sender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=200)),
            ],
        ),
    ]
