# Generated by Django 4.0.3 on 2022-03-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='receipient_location',
            field=models.CharField(choices=[('Nairobi', 'Nairobi'), ('M', 'Mombasa'), ('K', 'Kisumu'), ('E', 'Embu'), ('N', 'Nakuru')], max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='sender_location',
            field=models.CharField(choices=[('Nairobi', 'Nairobi'), ('M', 'Mombasa'), ('K', 'Kisumu'), ('E', 'Embu'), ('N', 'Nakuru')], max_length=100),
        ),
    ]
