# Generated by Django 4.0.3 on 2022-03-30 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_customer_receipient_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='receipient_location',
            field=models.CharField(choices=[('Nairobi', 'Nairobi'), ('Mombasa', 'Mombasa'), ('Kisumu', 'Kisumu'), ('Embu', 'Embu'), ('Nakuru', 'Nakuru')], max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='sender_location',
            field=models.CharField(choices=[('Nairobi', 'Nairobi'), ('Mombasa', 'Mombasa'), ('Kisumu', 'Kisumu'), ('Embu', 'Embu'), ('Nakuru', 'Nakuru')], max_length=100),
        ),
    ]
