# Generated by Django 4.0.3 on 2022-03-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_customer_receipient_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='parcel_weight',
            field=models.CharField(choices=[('0-1 kgs', '0-1 kgs'), ('S', '2-5 kgs'), ('T', '6-10 kgs')], max_length=100),
        ),
    ]
