# Generated by Django 4.0.3 on 2022-04-02 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_customer_parcel_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='order_id',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
