# Generated by Django 4.0.3 on 2022-04-02 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_customer_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='order_id',
        ),
    ]
