# Generated by Django 4.0.3 on 2022-04-02 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_customer_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='sender_location',
            new_name='pickup_location',
        ),
    ]
