# Generated by Django 4.0.3 on 2022-04-02 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_sender_location_customer_pickup_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='receipient_location',
            new_name='destination_location',
        ),
    ]
