# Generated by Django 4.0.3 on 2022-04-02 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_receipient_location_customer_destination_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='receipient_lname',
            new_name='receipient_name',
        ),
    ]
