# Generated by Django 4.0.3 on 2022-04-02 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_receipient_lname_customer_receipient_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='parcel_weight',
            new_name='parcel_packages',
        ),
    ]
