# Generated by Django 4.0.3 on 2022-04-02 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_parcel_weight_customer_parcel_packages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='sender_fname',
        ),
        migrations.AlterField(
            model_name='customer',
            name='parcel_packages',
            field=models.CharField(choices=[('Small', 'Small'), ('Large', 'Large')], max_length=100),
        ),
    ]
