# Generated by Django 4.0.3 on 2022-04-02 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_customer_sender_fname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='parcel_description',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='receipient_fname',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='sender_lname',
        ),
    ]
