# Generated by Django 4.0.3 on 2022-04-02 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_customer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='parcel_packages',
            new_name='parcel_package',
        ),
    ]
